title: Eloquent Gargling
author: MarcoPerez23
email: marco.perezismatul@galileo.edu
description: > # this means to ignore newlines until "baseurl:"
Eloquent gargling at it's best!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  MarcoPerez23 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
